config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
   # KHS: agregar rutas url => controlador#acción que responde
   # Rutas Devise
   devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
   
   # Obtener información
   # get
   # Insertar información
   # post
   # Actualizar información
   # patch
   # Eliminar información
   # delete
   
   # HOME
   root to: "home#index" # Ruta base
   get "/home", to: "home#index"
   # Regresar a la página anterior
   get "/return_back/:default", to: "application#return_back", as:"return_back_or_default"
   
   # Readings (Text)
   get "readings", to: "readings#index" # Filtro: todas
   get "readings/read", to: "readings#index_read" # Filtro: leídas
   get "readings/unread", to: "readings#index_unread" # Filtro: nuevas (no leídas)
   get "readings/recommended", to: "readings#index_recommended" # Filtro: recomendadas
   get "readings/shared", to: "readings#index_shared" # Filtro: compartidas
   get "readings/uploaded", to: "readings#index_uploaded" # Filtro: subidas (por el usuario)
   # Reading: new/create
   get "readings/new", to: "readings#new"
   post "/texts", to: "readings#create"
   # Reading: show/read
   get "readings/:id", to: "readings#show", as: "readings_show"
   # Reading: edit/update
   get "readings/:id/edit", to: "readings#edit", as: "readings_edit"
   patch "readings/:id", to: "readings#update", as: :text
   # Reading: delete
   delete "readings/:id/delete", to: "readings#destroy", as: "readings_destroy"
      
   # Flashcards (UserWord, InteractedWord)
   get "flashcards", to: "flashcards#index" # Filtro: todas
   get "flashcards/next", to: "flashcards#index_next" # Filtro: siguiente repaso a tiempo
   get "flashcards/expired", to: "flashcards#index_expired" # Filtro: repaso caducado
   get "flashcards/standby", to: "flashcards#index_standby" # Filtro: repaso en espera
   get "flashcards/challenge", to: "flashcards#index_challenge" # Filtro: repaso de desafío
   # Flashcard: show/read
   get "flashcards/review/:filter/:size", to: "flashcards#review", as: "flashcards_review" # Repaso/Estudio de Tarjetas de Memoria
   
   # ¿En qué orden se va a listar?
   # ¿Una lista unificada marcada por conjuntos y que cada cambio de status se salga de show?
   # UserWord: show/read
   
   # Vocabulary / Word / Internal Services JS
   post "vocabulary/add_word_from_reading", to: "vocabulary#add_word_from_reading"
   post "vocabulary/update_word_from_flashcard", to: "vocabulary#update_word_from_flashcard" # Actualización de Tarjeta de Memoria
   post "vocabulary/add_words_from_test", to: "vocabulary#add_words_from_test" # Agregar palabras desde Test inicial
   # Vocabulary / Word / Services (Google Cloud Platform)
   post "vocabulary/word/translate", to: "vocabulary#translate_service"
   post "vocabulary/word/images", to: "vocabulary#images_service"
   post "vocabulary/word/text_to_speech", to: "vocabulary#text_to_speech_service"
   
   
   
   
   
   # Redirección de rutas
   get "/users", to: redirect("/")
   
   # Rutas de error
   # get '/foo', :to => redirect('/foo.html')
   get "*a", to: "errors#file_not_found"
   get "422", to: "errors#unprocessable"
   get "500", to: "errors#internal_server_error"
end

app/controllers/flashcards_controller.rb
#encoding: UTF-8
require_relative '../spaced_repetition/spaced_repetition'
# KHS: Controlador para flashcards
class FlashcardsController < ApplicationController
   before_action :authenticate_user!
   before_action :clean_return_back, only: [:index, :index_next, :index_expired, :index_standby, :index_challenge]
   
   # List All
   
   def index()
      interacted_words = find_flashcards_by(Const::ALL_FLASHCARDS_FILTER)
      @pagy, @interacted_words = pagy(interacted_words, items:10) # Paginación de textos
   end
   
   def index_next()
      interacted_words = find_flashcards_by(Const::NEXT_FLASHCARDS_FILTER)
      @pagy, @interacted_words = pagy(interacted_words, items:10) # Paginación de textos
   end
   
   def index_expired()
      interacted_words = find_flashcards_by(Const::EXPIRED_FLASHCARDS_FILTER)
      @pagy, @interacted_words = pagy(interacted_words, items:10) # Paginación de textos
   end
   
   def index_standby()
      interacted_words = find_flashcards_by(Const::STANDBY_FLASHCARDS_FILTER)
      @pagy, @interacted_words = pagy(interacted_words, items:10) # Paginación de textos
   end
   
   def index_challenge()
      interacted_words = find_flashcards_by(Const::CHALLENGE_FLASHCARDS_FILTER)
      @pagy, @interacted_words = pagy(interacted_words, items:10) # Paginación de textos
   end
   
   # Repaso de vocabulario
   
   def review()
      save_location(params[:save_location])
      
      # Flashcards: filter, size, index, ranking
      filter   = (params[:filter].nil? || params[:filter].empty?) ? 'none' : params[:filter]
      @size    = (params[:size].nil? || params[:size].empty?) ? 0 : params[:size].to_i
      @index   = (params[:index].nil? || params[:index].empty?) ? 1 : params[:index].to_i
      @ranking = (params[:ranking].nil? || params[:ranking].empty?) ? 0 : params[:ranking].to_i # Tarjetas correctas
      @exclude = (params[:exclude].nil? || params[:exclude].empty?) ? '' : params[:exclude].to_s #IDs a excluir
            
      @interacted_words = find_flashcards_by(filter, @size, @exclude.split(','))
      @current_interacted_word = (@interacted_words.nil? || @interacted_words.empty?) ? nil : @interacted_words.first
   end
   
   
   protected
   
   
   def find_flashcards_by(filter, size=-1, exclude=[])
      @filter = filter
      interacted_words = nil
      
      if (filter == Const::ALL_FLASHCARDS_FILTER)
         interacted_words = find_all_flashcards(size, exclude)
      elsif (filter == Const::NEXT_FLASHCARDS_FILTER)
         interacted_words = find_next_flashcards(size, exclude)
      elsif (filter == Const::EXPIRED_FLASHCARDS_FILTER)
         interacted_words = find_expired_flashcards(size, exclude)
      elsif (filter == Const::STANDBY_FLASHCARDS_FILTER)
         interacted_words = find_standby_flashcards(size, exclude)
      elsif (filter == Const::CHALLENGE_FLASHCARDS_FILTER)
         interacted_words = find_challenge_flashcards(size, exclude)
      end
      
      return interacted_words
   end
   
   # Find methods
   
   def find_all_flashcards(size, exclude)
      # Petición a DBMS para listas
      if (size <= 0 && exclude.size() == 0)
         return InteractedWord.where(user:current_user).order(user_next_review: :asc)
      end
      
      # Petición a DBMS para conjuntos con limite de 10 o 5 tarjetas y excluyendo IDs
      return InteractedWord.where(user:current_user).order(user_next_review: :asc).limit(size).where.not(id:exclude)
   end
   
   def find_next_flashcards(size, exclude)
      # Periodo de repaso de start_datetime a final_datetime (la diferencia es de DAYS_RANGE)
      start_datetime = InteractedWord.datetime_to_text(DateTime.now())
      final_datetime = InteractedWord.datetime_to_text(DateTime.now() + Const::DAYS_RANGE)
      
      # Petición a DBMS para listas
      if (size <= 0 && exclude.size() == 0)
         return InteractedWord.where(user:current_user).where("interacted_words.user_next_review >= '#{start_datetime}' AND interacted_words.user_next_review <= '#{final_datetime}'").order(user_next_review: :asc)
      end
      
      # Petición a DBMS para conjuntos con limite de 10 o 5 tarjetas y excluyendo IDs
      return InteractedWord.where(user:current_user).where("interacted_words.user_next_review >= '#{start_datetime}' AND interacted_words.user_next_review <= '#{final_datetime}'").order(user_next_review: :asc).limit(size).where.not(id:exclude)
   end
   
   def find_expired_flashcards(size, exclude)
      current_datetime = InteractedWord.datetime_to_text(DateTime.now())
      
      # Petición a DBMS para listas
      if (size <= 0 && exclude.size() == 0)
         return InteractedWord.where(user:current_user).where("interacted_words.user_next_review <= '#{current_datetime}'").order(user_next_review: :asc)
      end
      
      # Petición a DBMS para conjuntos con limite de 10 o 5 tarjetas y excluyendo IDs
      return InteractedWord.where(user:current_user).where("interacted_words.user_next_review <= '#{current_datetime}'").order(user_next_review: :asc).limit(size).where.not(id:exclude)
   end
   
   def find_standby_flashcards(size, exclude)
      range_datetime = InteractedWord.datetime_to_text(DateTime.now() + Const::DAYS_RANGE)
      
      # Petición a DBMS para listas
      if (size <= 0 && exclude.size() == 0)
         return InteractedWord.where(user:current_user).where("interacted_words.user_next_review >= '#{range_datetime}'").order(user_next_review: :asc)
      end
      
      # Petición a DBMS para conjuntos con limite de 10 o 5 tarjetas y excluyendo IDs
      return InteractedWord.where(user:current_user).where("interacted_words.user_next_review >= '#{range_datetime}'").order(user_next_review: :asc).limit(size).where.not(id:exclude)
   end
   
   def find_challenge_flashcards(size, exclude)
      interacted_words = InteractedWord.where(user:current_user).order(user_next_review: :asc)
      ids_array = Array.new()
      
      interacted_words.each do |interacted_word|
         if (interacted_word.difficulty() == Const::HIGH_DIFFICULTY)
            ids_array << interacted_word.id
         end
      end
      
      # Petición a DBMS para listas
      if (size <= 0 && exclude.size() == 0)
         return InteractedWord.where(id:ids_array).order(user_next_review: :asc)
      end
      
      # Petición a DBMS para conjuntos con limite de 10 o 5 tarjetas y excluyendo IDs
      return InteractedWord.where(id:ids_array).order(user_next_review: :asc).limit(size).where.not(id:exclude)
   end
   
end

app/views/flashcards/_flashcards_panel.html.erb
<div id="panel">

   <%# Breadcrumb %>
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-dark">
         <li class="breadcrumb-item plain text-light">
            <%= link_to t("home.title.#{current_user.role}"), home_path, "class"=>"text-saic text-light" %>
         </li>
         <li class="breadcrumb-item plain text-light" aria-current="page">
            <%= (filter == Const::ALL_FLASHCARDS_FILTER) ? t('flashcards.title') : t('flashcards.title') + " " + t("flashcards.badge.#{filter}.label").downcase %>
         </li>
      </ol>
   </nav>
   
   <%# Toolbar %>
   <div style="margin-bottom: 5px;" class="btn-toolbar justify-content-between" role="toolbar">
      <%# Filtros IZQ%>
      <div class="btn-group" role="group" aria-label="First group">
         <%# Todas %>
         <% value_class = "btn btn-secondary" %>
         <% value_class = (filter == Const::ALL_FLASHCARDS_FILTER) ? value_class+" disabled" : value_class %>
         <%= link_to t('button.flashcards.index.all.label'), flashcards_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.flashcards.index.all.tooltip'), "disabled"=>(filter == Const::ALL_FLASHCARDS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         <% unless (current_user.code == Const::CONTROL_CODE) %> <%# Ocultar para el grupo de control %>
            <%# Próximas %>
            <% value_class = "btn btn-secondary" %>
            <% value_class = (filter == Const::NEXT_FLASHCARDS_FILTER) ? value_class+" disabled" : value_class %>
            <%= link_to t('button.flashcards.index.next.label'), flashcards_next_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.flashcards.index.next.tooltip'), "disabled"=>(filter == Const::NEXT_FLASHCARDS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
            <%# Caducadas %>
            <% value_class = "btn btn-secondary" %>
            <% value_class = (filter == Const::EXPIRED_FLASHCARDS_FILTER) ? value_class+" disabled" : value_class %>
            <%= link_to t('button.flashcards.index.expired.label'), flashcards_expired_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.flashcards.index.expired.tooltip'), "disabled"=>(filter == Const::EXPIRED_FLASHCARDS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
            <%# En espera %>
            <% value_class = "btn btn-secondary" %>
            <% value_class = (filter == Const::STANDBY_FLASHCARDS_FILTER) ? value_class+" disabled" : value_class %>
            <%= link_to t('button.flashcards.index.standby.label'), flashcards_standby_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.flashcards.index.standby.tooltip'), "disabled"=>(filter == Const::STANDBY_FLASHCARDS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
            <%# Desafío %>
            <% value_class = "btn btn-secondary" %>
            <% value_class = (filter == Const::CHALLENGE_FLASHCARDS_FILTER) ? value_class+" disabled" : value_class %>
            <%= link_to t('button.flashcards.index.challenge.label'), flashcards_challenge_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.flashcards.index.challenge.tooltip'), "disabled"=>(filter == Const::CHALLENGE_FLASHCARDS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         <% end %>
      </div>
      
      <%# Opciones DER%>
      <div class="input-group">
         <%# Repasar 10 Tarjetas %>
         <%size = @interacted_words.size() >= 10 ? 10 : @interacted_words.size()%>
         <%= link_to t('button.flashcards.review.ten.label'), flashcards_review_path(filter, size), method: :get, "class"=>"btn btn-success text-saic", "title"=>t('button.flashcards.review.ten.tooltip'), data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         &nbsp
         <%# Repasar 5 Tarjetas %>
         <%size = @interacted_words.size() >= 5 ? 5 : @interacted_words.size()%>
         <%= link_to t('button.flashcards.review.five.label'), flashcards_review_path(filter, size), method: :get, "class"=>"btn btn-secondary text-saic", "title"=>t('button.flashcards.review.five.tooltip'), data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
      </div>
   </div>
   
   
   <%# Mensajes del panel %>
   <% if (@filter == Const::EXPIRED_FLASHCARDS_FILTER && @interacted_words.size() != 0) %>
      <div class="alert alert-danger annotation" role="alert">
         <h4 class="alert-heading">
            <%= t('alert.flashcards.expired.title') %>
         </h4>
         <%= t('alert.flashcards.expired.body') %>
      </div>
   <% elsif (@filter == Const::NEXT_FLASHCARDS_FILTER && @interacted_words.size() != 0) %>
      <div class="alert alert-success annotation" role="alert">
         <h4 class="alert-heading">
            <%= t('alert.flashcards.next.title') %>
         </h4>
         <%= t('alert.flashcards.next.body') %>
      </div>
   <% elsif (@filter == Const::STANDBY_FLASHCARDS_FILTER && @interacted_words.size() != 0) %>
      <div class="alert alert-secondary annotation" role="alert">
         <h4 class="alert-heading">
            <%= t('alert.flashcards.standby.title') %>
         </h4>
         <%= t('alert.flashcards.standby.body') %>
      </div>
   <% elsif (@filter == Const::CHALLENGE_FLASHCARDS_FILTER && @interacted_words.size() != 0) %>
      <div class="alert alert-info annotation" role="alert">
         <h4 class="alert-heading">
            <%= t('alert.flashcards.challenge.title') %>
         </h4>
         <%= t('alert.flashcards.challenge.body') %>
      </div>
   <% end %>
   
   
   <%# Lista de tarjetas de memoria %>
   <div class="list-group">
      <% @interacted_words.each do |interacted_word| %>
      
         <%# Tarjeta (Item)%>
         <a href="" class="list-group-item list-group-item-action" data-disable-with='<span class="text-saic"><%=t('button.loading')%></span> <div class="spinner-grow spinner-grow-sm" role="status"></div>'>
            <div class="d-flex justify-content-between align-items-center">
               
               <%# Badges IZQ %>
               <div style="width: fit-content; vertical-align: middle; text-align: left;">
                  <%# Tag status %>
                  <% status = interacted_word.status() %>
                  <% status_badge = "badge badge-pill badge-danger annotation" if (status == Const::EXPIRED_STATUS) %>
                  <% status_badge = "badge badge-pill badge-success annotation" if (status == Const::NEXT_STATUS) %>
                  <% status_badge = "badge badge-pill badge-secondary annotation" if (status == Const::STANDBY_STATUS) %>
                  <span class="<%=status_badge%>" title="<%=t("flashcards.badge.#{status}.tooltip")%>">
                     <%=t("flashcards.badge.#{status}.symbol")%>
                  </span>
                  &nbsp
                  <%# Title %>
                  <span class="mb-1 title-large"> <%=current_user.user_words.find(interacted_word.user_word_id).word%> </span>
               </div>
               
               <%# Badges DER %>
               <div style="width: fit-content; vertical-align: middle; text-align: right;">
                  <%# Tag review (days until next review) %>
                  <% review_badge = "text-danger annotation" if (status == Const::EXPIRED_STATUS) %>
                  <% review_badge = "text-success annotation" if (status == Const::NEXT_STATUS) %>
                  <% review_badge = "text-secondary annotation" if (status == Const::STANDBY_STATUS) %>
                  <span class="<%=review_badge%>" title="<%=t("flashcards.badge.#{status}.tooltip")%>">
                     <% days = interacted_word.days_until_next_review() %>
                     <%= t("flashcards.badge.time.#{status}.label") + " " + InteractedWord.days_to_text(days) %>
                  </span>
                  
                  <%# Tag difficulty %>
                  <% difficulty = interacted_word.difficulty() %>
                  <% difficulty_badge = "badge badge-info plain" if (difficulty == Const::LOW_DIFFICULTY) %>
                  <% difficulty_badge = "badge badge-info plain" if (difficulty == Const::MEDIUM_DIFFICULTY) %>
                  <% difficulty_badge = "badge badge-info plain" if (difficulty == Const::HIGH_DIFFICULTY) %>
                  <span class="<%=difficulty_badge%>" title="<%=t("flashcards.badge.difficulty.#{difficulty}.tooltip")%>">
                     <%=t("flashcards.badge.difficulty.#{difficulty}.label")%>
                  </span>
               </div>
            </div>
         </a>
         
      <% end %>
      
   </div>
   
   
   <%# Footer sin|con contenido %>
   <% if (@interacted_words.size == 0) %>
      <div id="footer">
         <p>
            <h1 class="title-large-bold">Sin contenido.</h1>
            <span class="plain">No hay contenido en esta sección. </span>
            <img id="error_image" src="<%=asset_path('without_content.png')%>" alt="Sin contenido" />
            <span class="annotation"></span>
         </p>
      </div>
   <%else%>
      <div id="footer">
         <%== pagy_bootstrap_nav(@pagy) %>
      </div>
   <% end %>
</div>

app/views/flashcards/index.html.erb
<%= content_for(:title, t("flashcards.title")) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "flashcards/flashcards_panel", filter: @filter %>
   
</div>

app/views/flashcards/index_challenge.html.erb
<%= content_for(:title, t("flashcards.title") + " " + t("flashcards.badge.challenge.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "flashcards/flashcards_panel", filter: @filter %>
   
</div>

app/views/flashcards/index_expired.html.erb
<%= content_for(:title, t("flashcards.title") + " " + t("flashcards.badge.expired.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "flashcards/flashcards_panel", filter: @filter %>
   
</div>

app/views/flashcards/index_next.html.erb
<%= content_for(:title, t("flashcards.title") + " " + t("flashcards.badge.next.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "flashcards/flashcards_panel", filter: @filter %>
   
</div>

app/views/flashcards/index_standby.html.erb
<%= content_for(:title, t("flashcards.title") + " " + t("flashcards.badge.standby.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "flashcards/flashcards_panel", filter: @filter %>
   
</div>