config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
   # KHS: agregar rutas url => controlador#acción que responde
   # Rutas Devise
   devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
   
   # Obtener información
   # get
   # Insertar información
   # post
   # Actualizar información
   # patch
   # Eliminar información
   # delete
   
   # HOME
   root to: "home#index" # Ruta base
   get "/home", to: "home#index"
   # Regresar a la página anterior
   get "/return_back/:default", to: "application#return_back", as:"return_back_or_default"
   
   # Readings (Text)
   get "readings", to: "readings#index" # Filtro: todas
   get "readings/read", to: "readings#index_read" # Filtro: leídas
   get "readings/unread", to: "readings#index_unread" # Filtro: nuevas (no leídas)
   get "readings/recommended", to: "readings#index_recommended" # Filtro: recomendadas
   get "readings/shared", to: "readings#index_shared" # Filtro: compartidas
   get "readings/uploaded", to: "readings#index_uploaded" # Filtro: subidas (por el usuario)
   # Reading: new/create
   get "readings/new", to: "readings#new"
   post "/texts", to: "readings#create"
   # Reading: show/read
   get "readings/:id", to: "readings#show", as: "readings_show"
   # Reading: edit/update
   get "readings/:id/edit", to: "readings#edit", as: "readings_edit"
   patch "readings/:id", to: "readings#update", as: :text
   # Reading: delete
   delete "readings/:id/delete", to: "readings#destroy", as: "readings_destroy"
      
   # Flashcards (UserWord, InteractedWord)
   get "flashcards", to: "flashcards#index" # Filtro: todas
   get "flashcards/next", to: "flashcards#index_next" # Filtro: siguiente repaso a tiempo
   get "flashcards/expired", to: "flashcards#index_expired" # Filtro: repaso caducado
   get "flashcards/standby", to: "flashcards#index_standby" # Filtro: repaso en espera
   get "flashcards/challenge", to: "flashcards#index_challenge" # Filtro: repaso de desafío
   # Flashcard: show/read
   get "flashcards/review/:filter/:size", to: "flashcards#review", as: "flashcards_review" # Repaso/Estudio de Tarjetas de Memoria
   
   # ¿En qué orden se va a listar?
   # ¿Una lista unificada marcada por conjuntos y que cada cambio de status se salga de show?
   # UserWord: show/read
   
   # Vocabulary / Word / Internal Services JS
   post "vocabulary/add_word_from_reading", to: "vocabulary#add_word_from_reading"
   post "vocabulary/update_word_from_flashcard", to: "vocabulary#update_word_from_flashcard" # Actualización de Tarjeta de Memoria
   post "vocabulary/add_words_from_test", to: "vocabulary#add_words_from_test" # Agregar palabras desde Test inicial
   # Vocabulary / Word / Services (Google Cloud Platform)
   post "vocabulary/word/translate", to: "vocabulary#translate_service"
   post "vocabulary/word/images", to: "vocabulary#images_service"
   post "vocabulary/word/text_to_speech", to: "vocabulary#text_to_speech_service"
   
   
   
   
   
   # Redirección de rutas
   get "/users", to: redirect("/")
   
   # Rutas de error
   # get '/foo', :to => redirect('/foo.html')
   get "*a", to: "errors#file_not_found"
   get "422", to: "errors#unprocessable"
   get "500", to: "errors#internal_server_error"
end

app/controllers/readings_controller.rb
#encoding: UTF-8
require_relative '../text_recommendation/text_recommendation'
require_relative '../spaced_repetition/spaced_repetition'
# KHS: Controlador para readings
class ReadingsController < ApplicationController
   before_action :authenticate_user!
   before_action :verify_associated_texts, only: [:index, :index_read, :index_unread, :index_recommended, :index_shared, :index_uploaded]
   before_action :clean_return_back, only: [:index, :index_read, :index_unread, :index_recommended, :index_shared, :index_uploaded]
   before_action :find, only: [:show, :edit, :update, :destroy]
   
   @text = nil # current_text
   
   
   # List All
   
   def index()
      list_by(Const::ALL_READINGS_FILTER)
   end
   
   def index_read()
      list_by(Const::READ_READINGS_FILTER)
   end
   
   def index_unread()
      list_by(Const::UNREAD_READINGS_FILTER)
   end
   
   def index_recommended()
      # Obtener textos recomendados y no leídos
      associated_texts = AssociatedText.where(user:current_user).where(recommendation: true).where(status: Const::UNREAD_STATUS)
      # Obtener palabra del usuario con el próximo repaso más antiguo/próximo
      interacted_words = InteractedWord.where(user:current_user).order(user_next_review: :asc).limit(1)
      interacted_word = interacted_words.first
      # Bandera que indica si ya se ha lanzado el Algoritmo TR en la sesión actual o no
      already_recommended = session[:already_recommended].nil? ? false : session[:already_recommended]
      
      # El Algoritmo de Recomendación de Textos (Algoritmo TR) se lanza sólo una vez por sesión si la cantidad de textos recomendados y no leídos es menor a TEXTS_QUANTITY_VALIDATION (1 texto) o si los dias hasta el siguiente repaso de una palabra del usuario es menor a DAYS_UNTIL_REVIEW_VALIDATION (7 días).
      
      if ((associated_texts.size() < TR::TEXTS_QUANTITY_VALIDATION || interacted_word.days_until_next_review() < TR::DAYS_UNTIL_REVIEW_VALIDATION) && (! already_recommended))
         # Almacenamiento en HASH de session de bandera para lanzar el algoritmo una vez por sesión
         session[:already_recommended] = TR::ALREADY_RECOMMENDED_VALIDATION
         # Crear objeto especial para el Algoritmo TR: User to TRUser
         tr_user = TRUser.new(
            current_user.id,
            current_user.email,
            current_user.first_name,
            current_user.last_name,
            current_user.birthdate,
            current_user.cefr_profiles.first.id,
            current_user.cefr_profiles.first.level,
            current_user.cefr_profiles.first.name,
            current_user.cefr_profiles.first.description,
            current_user.genders.first.id,
            current_user.genders.first.name,
            current_user.genders.first.description,
            current_user.learning_styles.first.id,
            current_user.learning_styles.first.name,
            current_user.learning_styles.first.description
         )
         # Instanciar la clase del Algoritmo TR
         text_recommendation = TextRecommendation.new()
         # Invocar la generación de recomendaciones de texto
         tr_texts = text_recommendation.generate_text_recommendations(tr_user)
         # Limpiar las recomendaciones de texto antiguas
         text_recommendation.update_text_recommendations(tr_texts, tr_user)
      else
         puts "El Algoritmo TR ya fue ejecutado en esta sesión."
      end
      
      list_by(Const::RECOMMENDED_READINGS_FILTER)
   end
   
   def index_shared()
      list_by(Const::SHARED_READINGS_FILTER)
   end
   
   def index_uploaded() # Uploaded / Owner
      list_by(Const::UPLOADED_READINGS_FILTER)
   end
   
   # New / create
   
   def new()
      save_location(params[:save_location])
      
      @text = Text.new()
      # Recuperar valores previos del formulario, si existen
      @text.title = params[:title]
      @text.body  = params[:body]
      @text.cefr_profile_id = params[:cefr_profile_id]
   end
   
   def create()
      text_params = params[:text]
      @text = nil
   
      title = text_params[:title] # Título de la lectura
      body  = text_params[:body] # Cuerpo de la lectura (texto / lectura)
      tokens = 0 # Número de palabras en el texto
      types = 0 # Número de palabras no repetidas en el texto
      lemmas = 0 # Número de lemas no repetidos en el texto
      vocabulary = Array.new() # Vocabulario (array de Expressions)
      cefr_profile_id = text_params[:cefr_profile_id] # ID del Perfil MCER
            
      # Generar vocabulario
      unless ((body.nil? || body.empty?) || (title.nil? || title.empty?) || (cefr_profile_id.nil? || cefr_profile_id.empty?))
         tokens = Text.count_tokens(body)
         vocabulary  = Text.create_vocabulary(body)
         
         unless (vocabulary.nil? || !vocabulary.length==0)
            types  = Text.count_types(vocabulary)
            lemmas = Text.count_lemmas(vocabulary)
         else
            redirect_to readings_new_path(title:title, body:body, cefr_profile_id:cefr_profile_id, save_location: false), alert: t('alert.freeling.invalid') and return
         end
      end
      
      # Crear Text
      @text = Text.create(title:title, body:body, tokens:tokens, types:types, lemmas:lemmas, cefr_profile_id:cefr_profile_id)
      
      if (@text.valid?)
         # Crear relación Text / ProfiledText / CefrProfile
         @text.insert_cefr_association()
         
         # Crear relación Text / AssociatedText / User
         @text.insert_text_association(current_user, true)
      
         # Vocabulario a base de datos
         vocabulary.each do |expression|
            # Crear TextWord
            text_word = nil
            
            unless (TextWord.where(word:expression.word).any?)
               text_word = TextWord.create(word:expression.word, lemma:expression.lemma)
            else
               text_word = TextWord.find_by(word:expression.word)
            end
            
            # Crear relación Text / AssociatedWord / TextWord
            @text.insert_word_association(text_word, false, expression.word_frequency, expression.lemma_frequency)
         end
         
         redirect_to readings_uploaded_path, notice: t('alert.reading.created') # ORDER BY create_at desc or id
      else
         redirect_to readings_new_path(title: title, body: body, cefr_profile_id: cefr_profile_id, save_location: false), alert: create_alert(@text)
      end
   end
   
   # Show / read
   
   def show()
      save_location(params[:save_location])
      
      @text.update_status(current_user, Const::READ_STATUS)
   end
   
   # Edit / update
   
   def edit()
      save_location(params[:save_location])
      
      # # Recuperar valores previos del formulario, si existen
      @text.title = (params[:title].nil? || params[:title].empty?) ? @text.title : params[:title]
      @text.body  = (params[:body].nil? || params[:body].empty?) ? @text.body : params[:body]
      @text.cefr_profile_id = (params[:cefr_profile_id].nil? || params[:cefr_profile_id].empty?) ? @text.cefr_profile_id : params[:cefr_profile_id]
      
      
   end
   
   def update()
      text_params = params[:text]
      
      title = text_params[:title] # Título de la lectura
      body  = text_params[:body] # Cuerpo de la lectura (texto / lectura)
      tokens = 0 # Número de palabras en el texto
      types = 0 # Número de palabras no repetidas en el texto
      lemmas = 0 # Número de lemas no repetidos en el texto
      vocabulary = Array.new() # Vocabulario (array de Expressions)
      cefr_profile_id = text_params[:cefr_profile_id] # ID del Perfil MCER
      
      # Generar vocabulario
      unless ((body.nil? || body.empty?) || (title.nil? || title.empty?) || (cefr_profile_id.nil? || cefr_profile_id.empty?))
         tokens = Text.count_tokens(body)
         vocabulary  = Text.create_vocabulary(body)
         
         unless (vocabulary.nil? || !vocabulary.length==0)
            types  = Text.count_types(vocabulary)
            lemmas = Text.count_lemmas(vocabulary)
         else
            redirect_to readings_edit_path(title: title, body: body, cefr_profile_id: cefr_profile_id, save_location: false), alert: t('alert.freeling.invalid') and return
         end
      end
      
      # Actualizar Text
      is_update = @text.update(title:title, body:body, tokens:tokens, types:types, lemmas:lemmas, cefr_profile_id:cefr_profile_id)
      
      if (is_update)
         # Actualizar relación Text / ProfiledText / CefrProfile
         @text.update_cefr_association()
         
         # Actualizar relación Text / AssociatedText / User
         # @text.insert_text_association(current_user, true)
         
         # Eliminar relaciones anteriores del vocabulario
         @text.delete_all_word_associations()
         
         # Vocabulario a base de datos
         vocabulary.each do |expression|
            # Crear TextWord
            text_word = nil
            
            unless (TextWord.where(word:expression.word).any?)
               text_word = TextWord.create(word:expression.word, lemma:expression.lemma)
            else
               text_word = TextWord.find_by(word:expression.word)
            end
            
            # Crear relación Text / AssociatedWord / TextWord
            @text.insert_word_association(text_word, false, expression.word_frequency, expression.lemma_frequency)
         end
         
         # @text indica el texto a visualizar
         # save_location parametro que indica si se almacena la URL para volver atrás
         redirect_to return_back_or_default_path(readings_uploaded_path, save_location: false), notice: t('alert.reading.updated')
      else
          # Si alguno de los campos está vacío, no se va actualizar y se deben mostrar los mensajes de error
         temp_text = Text.new()
         temp_text.title = title
         temp_text.body = body
         temp_text.cefr_profile_id = cefr_profile_id
         temp_text.valid?
         

app/views/readings/_reading_form.html.erb
<div id="panel">

   <%# Breadcrumb %>
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-dark">
         <li class="breadcrumb-item plain text-light">
            <%= link_to t("home.title.#{current_user.role}"), home_path, "class"=>"text-light text-saic" %> </li>
         <li class="breadcrumb-item plain text-light">
            <%= link_to t('readings.title'), readings_path, "class"=>"text-light text-saic" %> </li>
         <li class="breadcrumb-item plain text-light" aria-current="page">
            <%= t('reading.new.title') if (action == 'new') %>
            <%= t('reading.edit.title') if (action == 'edit') %> </li>
      </ol>
   </nav>
   
   <%= form_with(model: @text, local: true) do |form| %>
      
      <%# Toolbar %>
      <div style="margin-bottom: 5px;" class="btn-toolbar justify-content-between" role="toolbar">
         <%# Opciones IZQ %>
         <div class="btn-group" role="group" aria-label="First group">
            <%# Back %>
            <%= link_to t('button.back.symbol') + t('button.back.label'), return_back_or_default_path(readings_path), method: :get, "class"=>"btn btn-dark text-saic", "title"=>t('button.back.tooltip') %>
         </div>
         
         <%# Opciones DER %>
         <div class="input-group">
            <% if (action == 'new') %> <%# New reading %>
               <button class="btn btn-success text-saic" type="button" data-toggle="modal" data-target="#openNewReading" title="<%=t('button.readings.create.tooltip')%>"> <%=t('button.readings.create.label')%> </button>
            <% else %> <%# Update reading (action == 'update')%>
               <button class="btn btn-success text-saic" type="button" data-toggle="modal" data-target="#openEditReading" title="<%=t('button.readings.update.tooltip')%>"> <%=t('button.readings.update.label')%> </button>
               &nbsp
               <button type="button" class="btn btn-secondary text-saic" title="<%=t("button.cancel.tooltip")%>" onclick="window.location.href='<%=return_back_or_default_path(readings_uploaded_path)%>'"> <%=t("button.cancel.label")%> </button>
            <% end %>
            &nbsp
         </div>
      </div>
      
      <%# Reader / Text Card %>
      <article class="card">
         <div class="card-header reader-header">
            <h1 class="text-rh"> <%=form.text_field :title, "id"=>"title_reading", "placeholder"=>t('form.text.title.label'), "title"=>t('form.text.title.tooltip')%> </h1>
         </div>
         <div class="card-body reader-body">
            <%# Descripciones %>
            <div class="col1_form" style="background-color: transparent;">
               <p class="annotation text-dark"> <%=t('form.text.body.description').html_safe%> </p>
            </div>
            <%# MCER Warning%>
            <p class="plain text-danger"> <%=t('form.text.cefr.update') if (action == 'edit')%> </p>
            <%# TextArea %>
            <%=form.text_area :body, "id"=>"body_reading", "class"=>"text-rb", "placeholder"=>t('form.text.body.label'), "title"=>t('form.text.body.tooltip') %>
            <%# MCER %>
            <table class="table_form" style="border: none;">
               <tr>
                  <td class="col1_form" style="background-color: transparent;">
                     <label class="label text-saic text-dark"> <%=t('form.text.cefr.label')%> </label>
                  </td>
                  <td class="col1_form" style="background-color: transparent;">
                     <% if (action_name == 'new') %> <%# New reading %>
                        <%= form.collection_select :cefr_profile_id, CefrProfile.order(:level).all(), :id, :level_name, "class"=>"text-dark", include_blank: t('form.text.select.blank') %>
                     <% else %> <%# Update reading (action == 'update')%>
                        <%= form.collection_select :cefr_profile_id, CefrProfile.order(:level).all(), :id, :level_name, "class"=>"text-dark", include_blank: t('form.text.select.blank') %>
                     <% end %>
                     <p class="annotation text-dark">
                        <%=t('form.text.cefr.help')%>
                        <br>
                        <button type="button" class="btn btn-sm btn-link" data-toggle="modal" data-target="#openCefr" style="font-size: small;"> <%=t('form.text.cefr.link')%> </button>
                     </p>
                  </td>
               </tr>
            </table>
         </div>
      </article>
      
      <% if (action == 'new') %>
         <!-- Render modal: create reading-->
         <%= render "layouts/alert_modal", id:"openNewReading", type:"btn btn-success", message:t('alert.reading.create'), negative_button:t('button.negative'), possitive_button:t('button.readings.create.label'), path: :texts, method: :post, form: form %>
      <% else %>
         <!-- Render modal: update reading-->
         <%= render "layouts/alert_modal", id:"openEditReading", type:"btn btn-success", message:t('alert.reading.update'), negative_button:t('button.negative'), possitive_button:t('button.readings.update.label'), path: readings_edit_path, method: :post, form: form %>
      <% end %>
   <% end %>
</div>

app/views/readings/_readings_panel.html.erb
<div id="panel">

   <%# Breadcrumb %>
   <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-dark">
         <li class="breadcrumb-item plain text-light">
            <%= link_to t("home.title.#{current_user.role}"), home_path, "class"=>"text-light text-saic" %>
         </li>
         <li class="breadcrumb-item plain text-light" aria-current="page">
            <%= (filter == Const::ALL_READINGS_FILTER) ? t('readings.title') : t('readings.title') + " " + t("readings.badge.#{filter}.label").downcase %>
         </li>
      </ol>
   </nav>

   <%# Toolbar %>
   <div style="margin-bottom: 5px;" class="btn-toolbar justify-content-between" role="toolbar">
      <%# Filtros IZQ%>
      <div class="btn-group" role="group" aria-label="First group">
         <%# Todas %>
         <% value_class = "btn btn-secondary" %>
         <% value_class = (filter == Const::ALL_READINGS_FILTER) ? value_class+" disabled" : value_class %>
         <%= link_to t('button.readings.index.all.label'), readings_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.readings.index.all.tooltip'), "disabled"=>(filter == Const::ALL_READINGS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         <%# Leídas %>
         <% value_class = "btn btn-secondary" %>
         <% value_class = (filter == Const::READ_READINGS_FILTER) ? value_class+" disabled" : value_class %>
         <%= link_to t('button.readings.index.read.label'), readings_read_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.readings.index.read.tooltip'), "disabled"=>(filter == Const::READ_READINGS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         <%# No leídas / nuevas %>
         <% value_class = "btn btn-secondary" %>
         <% value_class = (filter == Const::UNREAD_READINGS_FILTER) ? value_class+" disabled" : value_class %>
         <%= link_to t('button.readings.index.unread.label'), readings_unread_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.readings.index.unread.tooltip'), "disabled"=>(filter == Const::UNREAD_READINGS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         <%# Recomendadas %>
         <% unless (current_user.code == Const::CONTROL_CODE) %> <%# Ocultar para el grupo de control %>
            <% value_class = "btn btn-secondary" %>
            <% value_class = (filter == Const::RECOMMENDED_READINGS_FILTER) ? value_class+" disabled" : value_class %>
            <%= link_to t('button.readings.index.recommended.label'), readings_recommended_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.readings.index.recommended.tooltip'), "disabled"=>(filter == Const::RECOMMENDED_READINGS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         <% end %>
         <%# Compartidas %>
         <%# <% value_class = "btn btn-secondary" %>
         <%# <% value_class = (filter == Const::SHARED_READINGS_FILTER) ? value_class+" disabled" : value_class %>
         <%# <%= link_to t('button.readings.index.shared.label'), readings_shared_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.readings.index.shared.tooltip'), "disabled"=>(filter == Const::SHARED_READINGS_FILTER) ? true : false, data: {disable_with: "<span id=\"text\">#{t('button.loading')}</span> <div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div>"} %>
         <%# Subidas / Propietario %>
         <% value_class = "btn btn-secondary" %>
         <% value_class = (filter == Const::UPLOADED_READINGS_FILTER) ? value_class+" disabled" : value_class %>
         <%= link_to t('button.readings.index.uploaded.label'), readings_uploaded_path, method: :get, "class"=>"#{value_class} text-saic", "title"=>t('button.readings.index.uploaded.tooltip'), "disabled"=>(filter == Const::UPLOADED_READINGS_FILTER) ? true : false, data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
      </div>
      
      <%# Opciones DER%>
      <div class="input-group">
         <%# Upload reading %>
         <%= link_to t('button.readings.new.label'), readings_new_path, method: :get, "class"=>"btn btn-success text-saic", "title"=>t('button.readings.new.tooltip'), data: {disable_with: "<div class=\"spinner-grow spinner-grow-sm\" role=\"status\"></div> <span id=\"text\">#{t('button.loading')}</span>"} %>
         &nbsp
      </div>
   </div>
   
   
   <%# Mensajes del panel %>
   <% if (filter == Const::RECOMMENDED_READINGS_FILTER && @associated_texts.size != 0) %>
      <div class="alert alert-warning annotation" role="alert">
         <h4 class="alert-heading">
            <%= t('alert.readings.recommended.title') %>
         </h4>
         <%= t('alert.readings.recommended.body') %>
      </div>
   <% elsif (filter == Const::UPLOADED_READINGS_FILTER && @associated_texts.size != 0) %>
      <div class="alert alert-success annotation" role="alert">
         <h4 class="alert-heading">
            <%= t('alert.readings.uploaded.title') %>
         </h4>
         <%= t('alert.readings.uploaded.body') %>
      </div>
   <% end %>


   <%# Lista de lecturas %>
   <div class="list-group">
      <% @associated_texts.each do |associated_text| %>
      
         <%# Lectura (Item)%>
         <a href="<%=readings_show_path(associated_text.text_id)%>" class="list-group-item list-group-item-action" data-disable-with='<span class="text-saic"><%=t('button.loading')%></span> <div class="spinner-grow spinner-grow-sm" role="status"></div>'>
            <div class="d-flex justify-content-between align-items-center">
            
               <%# Badges IZQ %>
               <div style="width: fit-content; vertical-align: middle; text-align: left;">
                  <%# Tag unread %>
                  <% if (associated_text.status == Const::UNREAD_STATUS) %>
                     <span class="badge badge-pill badge-primary annotation" title="<%=t('readings.badge.unread.tooltip')%>"> <%=t('readings.badge.unread.symbol')%> </span>
                     &nbsp
                  <% end %>
                  <%# Title %>
                  <span class="mb-1 title-large"> <%=current_user.texts.find(associated_text.text_id).title%> </span>
               </div>
               
               <%# Badges DER %>
               <div style="width: fit-content; vertical-align: middle; text-align: right;">
                  <%# Tag shared %>
                  <%# <% if (false) %> <%# associated_text.share == Const::SHARED_READINGS_FILTER %>
                     <%# <span class="badge badge-warning plain" title="readings.badge.shared.tooltip"> readings.badge.shared.symbol </span> %>
                  <%# <% end %>
                  <%# Tag recommendation %>
                  <% if (associated_text.recommendation)%>
                     <span class="badge badge-warning plain" title="<%=t('readings.badge.recommended.tooltip')%>"> <%= ((associated_text.recommendation_quality*10)/2).round(1).to_s + t('readings.badge.recommended.symbol') %> </span>
                  <% end %>
                  <%# Tag uploaded %>
                  <% if (associated_text.owner) %> <%# Uploaded / Owner %>
                     <span class="badge badge-success plain" title="<%=t('readings.badge.uploaded.tooltip')%>"> <%=t('readings.badge.uploaded.symbol')%> </span>
                  <% end %>
                  <%# Tag cefr profile %>
                  <span class="badge badge-info plain" title="<%=t('readings.badge.profile.tooltip')%>"> <%=current_user.texts.find(associated_text.text_id).cefr_profiles.first.level%> </span>
               </div>
            </div>
         </a>
         
      <% end %>
      
   </div>
   
   <%# Footer sin|con contenido %>
   <% if (@associated_texts.size == 0) %>
      <div id="footer">
         <p>
            <h1 class="title-large-bold">Sin contenido.</h1>
            <span class="plain">No hay contenido en esta sección. </span>
            <img id="error_image" src="<%=asset_path('without_content.png')%>" alt="Sin contenido" />
            <span class="annotation"></span>
         </p>
      </div>
   <%else%>
      <div id="footer">
         <%== pagy_bootstrap_nav(@pagy) %>
      </div>
   <% end %>

</div>

app/views/readings/edit.html.erb
<%= content_for(:title, t('reading.edit.title')) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "readings/reading_form", action:'edit' %>
   
</div>

<%# <script type="text/javascript">
   text_area = document.querySelector("#body_reading");
   text_area.addEventListener('input', autoResize, false);
   
   function autoResize() {
      this.style.height = 'auto';
      this.style.height = this.scrollHeight + 'px';
   }
</script> %>

<!-- Render modal: openCefr -->
<%= render "devise/registrations/cefr_modal", cefr_student:false %>

app/views/readings/index.html.erb
<%= content_for(:title, t("readings.title")) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "readings/readings_panel", filter: @filter %>
   
</div>

app/views/readings/index_read.html.erb
<%= content_for(:title, t("readings.title") + " " + t("readings.badge.read.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "readings/readings_panel", filter: @filter %>
   
</div>

app/views/readings/index_recommended.html.erb
<%= content_for(:title, t("readings.title") + " " + t("readings.badge.recommended.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "readings/readings_panel", filter: @filter %>
   
</div>

app/views/readings/index_shared.html.erb
<%= content_for(:title, t("readings.title") + " " + t("readings.badge.shared.label").downcase) %>
<div id="content">
   <%= render "layouts/alert_message" %>
   
   <%= render "readings/readings_panel", filter: @filter %>
   
</div>